myapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    path('category/<str:category>/', views.Category_page, name='Category_page'),
    path('blog/mine/', views.blog_ofMine, name='Category_page'),
    path('topic/<int:post_id>/', views.Topic, name='topic'),
    path('comment/<int:post_id>/', views.Handle_Comment, name='comment'),
    path('favorite/<int:user_id>/<int:post_id>/', views.handle_like, name='handle_like'),
    path('favorite_child/<int:user_id>/<int:post_id>/', views.handleLike_child, name='handle_like'),
    path('comment_child/<int:post_id>/<int:comment_id>/', views.Handle_CommentChild, name='comment_child'),
    path('comment_tag/<int:post_id>/<int:comment_id>/<int:user_id>/<str:comment_tag>/', views.Handle_CommentTag, name='comment_tag'),
    path('login/', views.login, name='login'),
    path('user/profile/<int:user_id>/', views.Profile, name='Profile'),
    path('search/<str:search_value>/', views.SearchPage, name='SearchPage'),
    path('register/', views.register, name='register'),
    path('delete/<int:post_id>/', views.delete_post, name='delete_post'),
    path('update/<int:post_id>/', views.updatePost, name='update_post'),
    path('addpost/', views.AddPost, name='addpost'),
    path('addpost/<int:post_id>/', views.AddPost_Citation, name='addpost'),
    path('logout/', views.user_logout, name='logout')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
 
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# --------------------  BANNER HOME PAGE IMAGE -------------------   

class Image(models.Model):
    image = models.ImageField(upload_to='images')
    
    
# --------------------  USER PROFILE -------------------  

    
        
class Notification(models.Model):
    username = models.CharField(default='user', max_length=100)
    user_id = models.IntegerField(default=1)
    message = models.CharField(max_length=100, default='')
    created_at = models.DateTimeField(default=timezone.now)
    to = models.CharField(max_length=50, default='')
    image = models.ImageField(upload_to='profiles/images',default='/static/images/user-icon.png')
    

class UserProfile(models.Model):
    choices_gender= (
        ('Nam','Nam'),
        ('Nữ','Nữ'),
        ('Khác','Khác')
    )
    choices_day = [(i, i) for i in range(1, 32)]  # Days from 1 to 31
    choices_month = [(i, i) for i in range(1, 13)]  # Months from 1 to 12
    day = models.IntegerField( choices= choices_day,default=1)
    month = models.IntegerField( choices= choices_month,default=1)
    year = models.IntegerField(default=2010)
    address = models.CharField(max_length=200, blank=True, null=True,default='')
    phone_number = models.CharField(blank=True,max_length=11, null=True,default= '')
    defaultName = models.CharField(blank=True,max_length=30,default= 'User')
    image = models.ImageField(upload_to='profiles/images',default='/static/images/user-icon.png')
    email = models.EmailField(blank= True, default='example@gmail.com')
    gender = models.CharField(default='Nam', choices=choices_gender,max_length=20)
    def __str__(self):
        return self.defaultName
    


# ---------------------COMMENT FATER -------------------   
class Comment(models.Model):
    user_id = models.IntegerField(default= 1)
    Commentid = models.IntegerField(default=1)
    topic_id = models.IntegerField(default=1)
    comment_content = models.TextField(default='')
    created_at = models.DateTimeField(default=timezone.now)
    reply_count = models.IntegerField(default= 0,blank= True)
    like = models.IntegerField(default = 0)
    dislike = models.IntegerField(default = 0)
    username= models.CharField(default= 'user',blank=True,max_length=50)
    image = models.ImageField(upload_to='comment/images',default='static/images/user-icon.png')

# --------------------  COMMENT CHILD -------------------   

class CommentChild(models.Model):
    tag = models.CharField(max_length=150,blank= True)
    user_id = models.IntegerField(default= 1)
    username= models.CharField(default= 'user',blank=True,max_length=50)
    image = models.ImageField(upload_to='comment/images',default='static/images/user-icon.png')
    topic_id = models.IntegerField(default=1)
    commentChild_id = models.IntegerField(default=1)
    responder = models.CharField(max_length=150)
    comment_content = models.TextField(default='')
    created_at = models.DateTimeField(default=timezone.now)
    like = models.IntegerField(default = 0)
    dislike = models.IntegerField(default = 0)
    
    
# -------------------------------------  POST  ---------------------------------   

class Post(models.Model):
    TOPIC_CHOICES = (
    ('du lịch', 'Du lịch'),
    ('thức ăn', 'Thức ăn'),
    ('công việc', 'Công việc'),
    ('giải trí', 'Giải trí'),
    )
    # lấy ra người dùng id đã đăng nhập hiện tại
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    citation_url = models.CharField(max_length=200, null=True,default= '')
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to='images/', null=True, blank=True)  # Thêm trường image
    topic = models.CharField(max_length=100, choices=TOPIC_CHOICES, default='du_lịch')
    author = models.ForeignKey(User,on_delete= models.CASCADE,default='user')

    def __str__(self):
        return self.title

myapp/views.py
from django.shortcuts import get_object_or_404, render, redirect,HttpResponse
from django.http import JsonResponse
from django.contrib.auth import authenticate, login as auth_login
from myapp.forms import SignupForm, LoginForm
from django.contrib.auth.models import User
from myapp.models import Image
from django.contrib.auth import logout
from myapp.forms import PostForm
from myapp.models import Post
from myapp.models import UserProfile
from myapp.models import Comment
from myapp.models import Notification

from myapp.models import CommentChild
from myapp.forms import CommentForm
from myapp.forms import CommentChildForm
from myapp.forms import UserProfileForm
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone

import pytz
# Create your views here.
# -----------------handle Home Page-------------------
def home(request):
    images = Image.objects.all() 
    user = request.user if request.user.is_authenticated else None
    # ảnh banner trang home
    current_user = request.user if request.user.is_authenticated else None
    # hiện tất cả bài blog
    context = {'images': images, 'user': user, 'current_user': current_user}
    return render(request, 'home.html', context)
# -----------------handle search Page-------------------
def SearchPage(request, search_value):
    PostsResult = Post.objects.filter(title= search_value)
    context = {'PostsResult': PostsResult,}
    return render(request, 'SearchPage.html', context)

# ----------------handle Blog of Mine Page-------------------
def blog_ofMine(request):
    if request.user.is_authenticated == False:
        return redirect('login')
    current_user = request.user if request.user.is_authenticated else None
    posts = Post.objects.filter(author= request.user)
    context = {'posts': posts,'current_user':current_user}
    return render(request, 'blog_ofMine.html', context)

# -----------------handle Profile Page-------------------
def Profile(request, user_id):
    if not request.user.is_authenticated:
        return redirect('login')
    current_user = request.user if request.user.is_authenticated else None
    DefaultProfile = get_object_or_404(UserProfile, id=user_id)
        
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=DefaultProfile)
        # save image and username to Comment
        # check form valid
        if form.is_valid():
            FormDB = form.save(commit=False)
            FormDB.id = user_id
            form.save()
            if DefaultProfile.image:
                Comment.objects.create(
                    user_id=current_user.id,
                    image=form.cleaned_data['image'],
                    username=current_user.username,
                )
                CommentChild.objects.create(
                    user_id=current_user.id,
                    image=form.cleaned_data['image'],

                    username=current_user.username,
                )
            messages.success(request, 'Lưu thông tin cá nhân thành công.')
            return redirect('home')
        else:
            print(form.errors)
    else:
        form = UserProfileForm(instance=DefaultProfile)     

    context = { 'current_user': current_user, 'form': form, 'DefaultProfile': DefaultProfile}
    return render(request, 'Profile.html', context)
        

# -----------------handle Delete Post -------------------

def delete_post(request, post_id):
    if request.user.is_authenticated == False:
        return redirect('login')
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        # Xóa bài post nếu yêu cầu là POST
        post.delete()
        return redirect('home')
# -----------------handle Update Post ------------------
        
def updatePost(request, post_id):
    if request.user.is_authenticated == False:
        return redirect('login')
    post = get_object_or_404(Post, id=post_id)
    current_user = request.user if request.user.is_authenticated else None
    
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('home')  # Assuming 'home' is the name of the view for your home page
    else:
        form = PostForm(instance=post, initial={'image': post.image})
    # check current ủe is exit
    
    context = {'form': form,'current_user':current_user}
    return render(request, 'update.html', context)

def Category_page(request,category):
    current_user = request.user if request.user.is_authenticated else None
    category_item = Post.objects.filter(topic=category)
    category_topics = Post.objects.filter(topic=category).first()
    
    context ={'current_user': current_user,
              
              'category': category_item,'category_topics': category_topics,}
    return render(request, 'Categories.html', context)
# add post
def AddPost(request):
    if not request.user.is_authenticated:
        return redirect('login')
    current_user = request.user if request.user.is_authenticated else None

    if request.method == 'POST':
        form = PostForm(request.POST,request.FILES)
        if form.is_valid():
            post = form.save(commit=False)  # Tạo một instance của bài viết nhưng chưa lưu vào database
            post.author = request.user  # Gán tác giả là username của người dùng hiện tại
             # Lưu bài viết vào database
            
            post.save()
            return redirect('home')  # Chuyển hướng về trang chủ sau khi lưu bài viết thành công
    else:
        form = PostForm()
    context = {'form': form,'current_user':current_user}
    return render(request, 'AddPost.html', context)
def AddPost_Citation(request,post_id):
    if not request.user.is_authenticated:
        return redirect('login')
    
    current_user = request.user if request.user.is_authenticated else None
    url = 'http://127.0.0.1:8000/topic/'

    if request.method == 'POST':
        form = PostForm(request.POST,request.FILES)
        if form.is_valid():
            post = form.save(commit=False)  # Tạo một instance của bài viết nhưng chưa lưu vào database
            post.author = request.user  # Gán tác giả là username của người dùng hiện tại
             # Lưu bài viết vào databas
            post.citation_url = url+str(post_id)+'/'
            post.save()
            return redirect('home')  # Chuyển hướng về trang chủ sau khi lưu bài viết thành công
    else:
        form = PostForm(initial={'citation_url': url+str(post_id)+'/'})
    context = {'form': form,'current_user':current_user}
    return render(request, 'citation.html', context)

# login
# 
def login(request):  
    
    if request.method == 'POST':
        form = LoginForm(request.POST)
        
        if form.is_valid():

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)  
                current_user = request.user if request.user.is_authenticated else None
                # Check if the user has a profile
                if not UserProfile.objects.filter(id=current_user.id).exists():
                    # Create a new profile for the user
                    UserProfile.objects.create(id = current_user.id)
                    
                return redirect('home')
            else:
                form.add_error(None, 'Invalid username or password. Please try again.')
    else:
        form = LoginForm()
        
    context = {'form': form}
    return render(request, 'login.html', context)
# register

def register(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            if User.objects.filter(username=username).exists():
                return render(request, 'register.html', {'form': form, 'error_message': 'Username already exists.'})
            else:
                # Username is unique, save the form data
                form.save()
                return redirect('login')
    else:
        form = SignupForm()
    context = {'form': form}
    return render(request, 'register.html', context)
# logout
def user_logout(request):
    logout(request)
    return redirect('home')
# topic

def handle_like (request,user_id,post_id ):
    CMT = Comment.objects.get(id = user_id)
    if 'Like' in request.POST:
        CMT.like +=1
        redirect('topic', post_id)  
    elif "Dislike" in request.POST:
        CMT.like += 1
    
    CMT.save()
    return redirect('topic', post_id)
        

def handleLike_child (request, user_id,post_id):
    CMTChild = CommentChild.objects.get(user_id = user_id)
    if 'Like' in request.POST:
        CMTChild.like +=1
        return redirect('topic', post_id)
    elif "Dislike" in request.POST:
        CMTChild.like += 1
    CMTChild.save()    
    return redirect('topic', post_id)
        
def Topic(request,post_id):
    current_user = request.user if request.user.is_authenticated else None
    post = Post.objects.get(id=post_id)
    Post_Comment =Comment.objects.filter(topic_id=post_id) 
    comment_temp = CommentForm()
    #child
    Post_CommentChild =CommentChild.objects.filter(topic_id=post_id)
    commentChild_temp = CommentChildForm()
    Profiles = UserProfile.objects.all()
    
    relate_to = Post.objects.filter(topic=post.topic)
    context = {'post': post,'relate_to': relate_to,
               'current_user':current_user, 
               'Post_CommentChild': Post_CommentChild, 
                'comment_temp':comment_temp,
                'Post_Comments':Post_Comment,
                'commentChild_temp':commentChild_temp,
                
                'Profiles':Profiles
            }

myapp/templates/AddPost.html
{% extends "base.html" %} {% block title %} home page {% endblock %}
{% block content %}
{% load static %}
<!-- body -->
<div class="w-full pt-[5rem] my-10">
    <!-- add post -->
    <!-- Blogs -->
    <h2 class="font-bold text-4xl my-6 text-gray-600 flex justify-center" id="PostNews">Tạo Blogs mới</h2>
    <!-- add blog content -->
    <form method="POST" enctype="multipart/form-data" class="p-6 mx-20 my-4 bg-white rounded-sm">
  {% csrf_token %}
  <div class="mb-4">
    <label for="title" class="block text-gray-700 text-sm font-bold mb-2">Chủ đề:</label>
    <input type="text" id="title" name="title" placeholder="Nhập chủ đề" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
  </div>
  <div class="mb-4">
    <label for="topic" class="block text-gray-700 text-sm font-bold mb-2">Phân loại:</label>
    <select name="topic" id="topic" class="border border-slate-500 px-2 py-1">
        <option value="du lịch">du lịch</option>
        <option value="thức ăn">thức ăn</option>
        <option value="công việc">công việc</option>
        <option value="giải trí">giải trí</option>
    </select>
  </div>
  <div class="mb-4">
    <label for="content" class="block text-gray-700 text-sm font-bold mb-2">Nội dung:</label>
    <textarea id="content" name="content" placeholder="Nhập nội dung" rows="6" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"></textarea>
  </div>
  <div class="mb-4">
    <label for="image" class="block text-gray-700 text-sm font-bold mb-2">Hình ảnh:</label>
    <input type="file" id="image" name="image" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
  </div>
 <div class="py-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="id_citation_url">Trích từ nguồn </label>
            <input type="text" name="citation_url" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" placeholder="Nhập URL ..."  maxlength="200" id="id_citation_url" fdprocessedid="55xp3m">
        </div>
  <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Thêm blog</button>
        </form>

</div>

{%endblock%}

myapp/templates/Categories.html
{% extends "base.html" %} {% block title %}Chủ đề  {% endblock %}
{% block content %}
    <div class="p-10 pt-[8rem]">
        <div class="w-full h-full ">
            <h2 class="text-4xl flex justify-center flex items-center text-gray-600">- Danh mục chủ đề về   
                 <p class="px-2 text-5xl text-red-500 uppercase">{% if  category_topics.topic %}
                    {{category_topics.topic}}
                        {%else %}
                    {{category.topic}}
                    {% endif %}
                    
                 </p>
               
                </h2>
           <div class="my-2 flex items-center flex-wrap">
              {% for post in category %}
                <div class="w-1/4 h-[25rem] overflow-hidden px-2 py-2">
                    <a href="{% url 'topic' post.id %}" class="w-full h-full">
                    <div class="rounded-sm w-full h-full bg-white shadow">
                        <img src="{{ post.image.url }}" class="w-full h-1/2" alt="">
                        <div class="px-4 py-1  h-full">
                        <p class="text-base font-bold whitespace-nowrap text-gray-700 overflow-hidden">Chủ đề: {{ post.title }}</p>
                        <p class="leading-5 text-sm h-[6.4rem] overflow-hidden text-ellipsis">- {{ post.content }}</p>
                            <div class="flex justify-between">
                                <form method="post" action="{% url 'delete_post' post.id %}" >
                                    {% csrf_token %}
                                    <input type="submit" value="xoá" class="text-red-500 cursor-pointer">
                                </form>
                                <a href='/update/{{post.id}}' class=" text-red-500 px-4">sửa</a>
                            </div>
                         <div class="flex items-center justify-between py-2 leading-4">
                            <p class="italic  text-[13.5px] flex items-end justify-end ">Tác giả: {{post.author}}</p>
                                <time class="italic  text-[13.5px] flex items-end justify-end ">{{post.created_at}}</time>
                        </div>
                        </div>

                    </div>
                </a>
                </div>
              {% endfor %}
           </div>
        </div>
    </div>
{%endblock%}

myapp/templates/Login.html
{% extends "base.html" %} {% block title %} home page {% endblock %}
{% block content %}

    <div class="container mt-[14rem] mx-auto w-[40rem]" id="container">
        <div class=" w-full  ">
            <form class="loginForm  w-full" method="post">
                <h1 class="text-xl py-2 font-bold">Đăng nhập</h1>
                
                
                <span> Nhập tên người dùng và mật khẩu đã đăng kí.</span>
                <div class="w-full">
                    {% csrf_token %}
                {{ form.as_p }}
                </div>
                <button class="text-blue-500 ml-auto">Quên mật khẩu?</button>
                <div class="flex justify-between w-full my-2">
                    <button type="submit" class="bg-red-600 text-sm rounded-md px-4 py-2  text-white">Đăng Nhập</button>
                    <div class="flex items-center">
                        <p class="pt-1 px-2 mt-0 mb-0 ">chưa có tài khoản? </p>
                        <a href="{% url 'register' %}"  class="my-0"><p class="p-0 text-blue-600 underline">Đăng Kí</p></a>
                    </div>
                </div>

            </form>
        </div>
       
    </div>
{%endblock%}

myapp/templates/Profile.html
{% extends "base.html" %} {% block title %}hồ sơ cá nhân {% endblock %}
{% block content %}
<div class="mt-36 ">
    <div class="flex  h-full">
        <div class="w-1/4 bg-white shadow mx-4 rounded-sm p-4 ">
            <h2 class="py-2 text-2xl tracking-wide text-gray-600 flex justify-center font-bold">Hồ sơ</h2>
            <div class="">
                <button class="w-full py-2 text-left hover:text-red-500">Thông tin cá nhân</button>
            </div>
        </div>
        <form  method="POST"   class="form_profile h-full w-full shadow bg-white rounded-sm mx-4 py-4 pl-16 pr-4" enctype="multipart/form-data">
            <h2 class="py-2 text-2xl text-gray-600 tracking-wide flex justify-center font-bold">Thông tin cá nhân</h2>
            <div class="w-full">
                <div class="flex  items-center py-3 w-full"> 
                    {% csrf_token %}
                    <label for="profilename" class="whitespace-nowrap  w-[110px] ">Tên :</label>
                    <div class="w-1/2">
                        {{form.defaultName}}
                        
                    </div>
                </div>
                <div class="flex  items-center py-3 w-full"> 
                    <label for="profilePhoneNumber" class="whitespace-nowrap  w-[110px] ">Số điện thoại :</label>
                    <div class="w-1/2">
                        {{form.phone_number}}
                        
                    </div>
                </div>
                <div class="flex  items-center py-3 w-full"> 
                    <label for="profileEmail" class="whitespace-nowrap  w-[110px] ">Email :</label>
                    <div class="w-1/2">
                        {{form.email}}
                        
                    </div>
                </div>
                 <div class="flex  items-center py-3 w-full"> 
                    <label for="profileEmail" class="whitespace-nowrap  w-[110px] ">Địa chỉ :</label>
                    <div class="w-1/2">
                        {{form.address}}
                        
                    </div>
                </div>
                <div class="flex  items-center py-3 "> 
                    <label for="usergender" class="w-[110px]">Giới tính :</label>
                    <select class="border border-gray-500 text-sm px-4 py-1.5" name="gender">
                <option value="Nam">Nam</option>
                <option value="Nữ">Nữ</option>
                <option value="Khác">Khác</option>
            </select>

                </div>
                <div class="flex birthday  items-center py-3"> 
                    <label for="day" class="w-[110px]">Ngày sinh :</label>
                    <div class="birthday-child">
                        {{form.day}}
                        {{form.month}}
                        {{form.year}}
                    </div>
                </div>
                <div class="flex  items-center py-3"> 
                    <label for="name" class="w-[110px]" >Ảnh đại diện :</label>
                    <div class="">
                        {{form.image}}
                    
                    </div>

                </div>

            </div>
            
            <button type="submit" class="bg-red-500 rounded-sm px-6 py-2 flex justify-end ml-auto text-white">Lưu </button>
        </form>
    </div>
    
</div>
<script>
    //<p class=" text-[12px] text-red-500">yêu cầu nhập trường này</p>
    var day = document.querySelector('.day')
    var month = document.querySelector('.month')
    var year = document.querySelector('.year')
    var months = ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"];
    var currentYear = new Date().getFullYear();
    for (var i = 1; i <= 31; i++) {
        var option = document.createElement("option");
        option.text = i;
        option.value = i
        day.add(option);
    }

    for (var i = 1; i <= months.length; i++) {
        var option = document.createElement("option");
        option.text = months[i];
        option.value = i
        month.add(option);
    }
    for (var i = currentYear; i >= currentYear - 100; i--) {
        var option = document.createElement("option");
        option.text = i;
        option.value = i
        year.add(option);
    }

</script>
{%endblock%}

myapp/templates/citation.html
{% extends "base.html" %} {% block title %}  Tạo blog {% endblock %}
{% block content %}
{% load static %}
<!-- body -->
<div class="w-full pt-[5rem] my-10">
    <!-- add post -->
    <!-- Blogs -->
    <h2 class="font-bold text-4xl my-6 text-gray-600 flex justify-center" id="PostNews">Tạo Blogs mới</h2>
    <!-- add blog content -->
    <form method="POST" enctype="multipart/form-data" class="p-6 mx-20 my-4 bg-white rounded-sm">
  {% csrf_token %}
  <div class="mb-4">
    <label for="title" class="block text-gray-700 text-sm font-bold mb-2">Chủ đề:</label>
    <input type="text" id="title" name="title" placeholder="Nhập chủ đề" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
  </div>
  <div class="mb-4">
    <label for="topic" class="block text-gray-700 text-sm font-bold mb-2">Phân loại:</label>
    <select name="topic" id="topic" class="border border-slate-500 px-2 py-1">
        <option value="du lịch">du lịch</option>
        <option value="thức ăn">thức ăn</option>
        <option value="công việc">công việc</option>
        <option value="giải trí">giải trí</option>
    </select>
  </div>
  <div class="mb-4">
    <label for="content" class="block text-gray-700 text-sm font-bold mb-2">Nội dung:</label>
    <textarea id="content" name="content" placeholder="Nhập nội dung" rows="6" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"></textarea>
  </div>
  <div class="mb-4">
    <label for="image" class="block text-gray-700 text-sm font-bold mb-2">Hình ảnh:</label>
    <input type="file" id="image" name="image" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
  </div>
 <div class="py-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="id_citation_url">Trích từ nguồn </label>
            {{form.citation_url}}
        </div>
  <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Thêm blog</button>
        </form>

</div>

{%endblock%}

myapp/templates/update.html
{% extends "base.html" %} {% block title %} cập nhật {% endblock %}
{% block content %}
{% load static %}
<!-- body -->

<div class="w-full pt-[5rem] my-10">
    <!-- add post -->
    <!-- Blogs --> 
    <h2 class="font-bold text-4xl my-6 text-gray-600 flex justify-center" id="PostNews">cập nhật Blogs</h2>
    <!-- add blog content -->
    <form method="post" class="p-6 mx-20 my-4 bg-white rounded-sm" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="py-1">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="id_title">chủ đề </label>
            {{form.title}}
        </div>
         <div class="py-1">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="id_topic">Phân loại </label>
            {{form.topic}}
        </div>

         <div class="py-1">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="id_content">Nội dung </label>
            {{form.content}}
        </div>
         <div class="py-1">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="id_image">Hình ảnh</label>
            {{form.image}}
        </div>
        <div class="py-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="id_citation_url">Trích từ nguồn </label>
            {{form.citation_url}}
        </div>
        <button type="submit " class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" >Save</button>
    </form>

</div>

{%endblock%}